version: '3.8'

services:
  # 1. Custom Flowise Image with a volume attached to the current directory
  flowise:
    image: flowiseai/flowise
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
    restart: unless-stopped

  # 2. MCP Service
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
      - "8005:3000"
    restart: unless-stopped

  # 3. Unstructured API service
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    ports:
      - "8003:8000"
    restart: unless-stopped

  # 4. LiteLLM service
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    command: --config litellm.yml
    ports:
      - "8004:4000"
    volumes:
      - ./litellm.yml:/app/config/litellm.yml
    restart: unless-stopped
    env_file:
      - .env

networks:
  default:
    name: flowise-network
